### ISSUE TITLE
The problem with card searching in HSBattlegroundsCardsSearch()

### ISSUE THREAD

**Issue by blizardinka** [FuzzyStatic/blizzard#19]
First I want to thank u for cool library. 
Second I am not sure that it doesn't work right and maybe I just made the mistake.
I want to search all 52 heroes from battlegrounds mode, but I get only 40. 
Maybe, do u know why it happens? 
`dat, _, err := blizz.HSBattlegroundsCardsSearch(
		context.Background(),
		"", "", "", "", "",
		[]int{}, []int{}, []int{}, 0, 0,
		[]hsgd.Tier{hsgd.TierHero},
		"", "", "",)`

**Comment by FuzzyStatic** [comment]
It looks like the default pageSize is limited to 40, if you increase pageSize to 52 or more you should get all results.
