### ISSUE TITLE
SC2 Ladder data for specific division's ladderID

### ISSUE THREAD

**Issue by w1ck3dg0ph3r** [FuzzyStatic/blizzard#21]
Hi!
There is an undocumented endpoint `/data/sc2/ladder/{ladderID}`, that can be used to get the player list for given division. While not 100% stable, it is widely used by sites like rankedftw and such.
Are you interested in a PR adding this endpoint?

**Comment by FuzzyStatic** [comment]
Sure, leave a comment about it's stability in the code and I'll take a look at the PR.
