### ISSUE TITLE
Add WoW Shadowland Updates

### ISSUE THREAD

**Issue by FuzzyStatic** [FuzzyStatic/blizzard#23]
Add new API calls for the WoW Shadowlands expansion: https://us.forums.blizzard.com/en/blizzard/t/wow-shadowlands-api-update-covenants-soulbinds-more/13385

**Comment by FuzzyStatic** [comment]
Covenant Complete, Tech Talent still needs to be done.

**Comment by NovikovRoman** [comment]
Hi! Need more help?

**Comment by FuzzyStatic** [comment]
Yes I do! I recently added a lot of structures but I have not had time to create the API calls that use them. Any help to get those working would be greatly appreciated!

**Comment by FuzzyStatic** [comment]
@NovikovRoman the structures that need API calls can be found at https://github.com/FuzzyStatic/blizzard/commit/3d28840e619f5c114b7273807fd0581324beff8c.

Some of them will need new constants to support them. If you do not want to do those ones, I can handle them myself if you do any of the other ones.

Thank you for all your other contributions!

**Comment by NovikovRoman** [comment]
Constants? For example what? For now, I'll just add tests.

**Comment by FuzzyStatic** [comment]
They added some search API calls. Part of the call looks for:

```
status.type | string |   | The status of the connected realm, UP or DOWN. (example search field)
-- | -- | -- | --
```

This will be a new status type constant for searches.

**Comment by NovikovRoman** [comment]
Ready to PR wowgd.
I missed  methods:
- WoWSpellSearch
- WoWMediaSearch
