### ISSUE TITLE
Missing information with the WoW Auction House

### ISSUE THREAD

**Issue by jpleau** [FuzzyStatic/blizzard#31]
Hello!

I noticed that the AuctionHouse.Auctions struct is missing some information.

Some examples:

```json
{"id":2064367368,"item":{"id":172329,"context":63,"bonus_lists":[6716,7193,1487]},"buyout":14770000,"quantity":1,"time_left":"VERY_LONG"}
```

The `bonus_list` would be nice to have, it allows us to calculate an item's item level, secondary stats, sockets, etc.

Also notice this one has `buyout` instead of `unit_price`. Materials have a `unit_price`, but everything else has a `buyout`. This is because of the new Auction House in patch 8.3, the UI is also different in-game for these 2 kind of auctions. It would be nice to have access to both `buyout` and `unit_price` via this package.

```json
{"id":2064014647,"item":{"id":82800,"context":0,"modifiers":[{"type":6,"value":58613}],"pet_breed_id":21,"pet_level":1,"pet_quality_id":3,"pet_species_id":1577}
```

Information on pets would be useful! They all have the same item id (82800, which is a cage). The information about the pet itself is in those other values (`pet_*`)

Hopefully these make sense!

Thanks

**Comment by FuzzyStatic** [comment]
@jpleau can you try the latest master commit and tell me if that resolves your issue?

**Comment by jpleau** [comment]
@FuzzyStatic The changes look good but I'm getting 401 Unauthorized when trying to test it. Same thing with the examples from the README. I noticed there were some refactoring between 1.1.4 and master, is there a new way to initialize the blizzard.Client ?

**Comment by FuzzyStatic** [comment]
@jpleau Yes, there was a small bug. Can you try again?

**Comment by jpleau** [comment]
@FuzzyStatic Both the changes to the auth and the auction house work perfectly, thanks !

**Comment by FuzzyStatic** [comment]
Thank you for your feedback! I've created release v1.1.5 with the changes.

**Comment by jpleau** [comment]
@FuzzyStatic I think you made a typo in the new tag, it says `v.1.1.5` instead of `v1.1.5` :)

**Comment by FuzzyStatic** [comment]
@jpleau TY, fixed.
