### ISSUE TITLE
WoW Auction House: Last-Modified response header

### ISSUE THREAD

**Issue by jpleau** [FuzzyStatic/blizzard#32]
Hi again!

Been working on my pet-project using your libray, everything is working great so far

In the WoW auction house API call, there is a header named "Last-Modified" in the response, that tells us when the data has been updated (it's usually once every hour).

Is there a way for me to access response headers from the api calls? I've quickly looked at the code and I couldn't find anything on my end.

Thanks!

**Comment by FuzzyStatic** [comment]
@jpleau I currently do not have this as part of functions. I will look into adding this.

**Comment by FuzzyStatic** [comment]
@jpleau Can you try this branch: https://github.com/FuzzyStatic/blizzard/tree/v1.2.0.

I've replaced returning `[]byte` with a new header structure with the API header information.

**Comment by jpleau** [comment]
I think there's a typo on this line: https://github.com/FuzzyStatic/blizzard/blob/fd50019a665308213454f8737a16eb555dac7617/v2/header.go#L67

It should be

```go

header.LastModified, err = time.Parse(time.RFC1123, httpHeader.Get(LastModified))
```

I think otherwise it looks good! Thank you for your quick answers this weekend :)

**Comment by FuzzyStatic** [comment]
@jpleau Release v1.2.0: https://github.com/FuzzyStatic/blizzard/releases/tag/v1.2.0

Thank you for your feedback!
