### ISSUE TITLE
Wrong time format used for date parsing for header.LastModified / Date

### ISSUE THREAD

**Issue by jpleau** [FuzzyStatic/blizzard#34]
Hi again

Been having weird issues today, and I think I found the cause:

in `header.go`:

```go
	if httpHeader.Get(HeaderKeyLastModified) != "" {
		header.LastModified, err = time.Parse(time.RFC1123, httpHeader.Get(HeaderKeyLastModified))
		if err != nil {
			header.LastModified = time.Time{}
		}
	}
```

If httpHeader.Get(HeaderKeyLastModified)  returns this string: "Sat, 3 Apr 2021 20:06:56 GMT" time.Parse() gives this error:

`parsing time "Sat, 3 Apr 2021 20:06:56 GMT" as "Mon, 02 Jan 2006 15:04:05 MST": cannot parse "3 Apr 2021 20:06:56 GMT" as "02"`

If instead of using `time.RFC1123` I try with a custom format `"Mon, _2 Jan 2006 15:04:05 MST"` then it works! Not sure if this still works if the day is > 9. I think so as it's how they handle it in Go's format.go

**Comment by FuzzyStatic** [comment]
@jpleau I've reached out on the Blizzard forums to get a definitive answer on what format is expected.

**Comment by FuzzyStatic** [comment]
@jpleau can you add you comments here: https://us.forums.blizzard.com/en/blizzard/t/header-datelastmodified-format-inconsistent/15803

**Comment by jpleau** [comment]
I really think the format they use is correct. It just doesn't fit right with Go's time.RFC1123 because it fails to account for the missing zero-padding, and adding the _ allows the date to be parsed.

For example in Python you could use %d, but it will work with or without a leading zero per the documentation. Been checking my logs and it only stopped working on April 1st (since I have been working on this for a few weeks. I didn't notice it before because we were at the end of march where padding zeroes aren't a problem.

**Comment by FuzzyStatic** [comment]
@jpleau I agree and I can make the change, but I'd like to see if the Blizzard devs can confirm their intent before I make any more changes.

If you want you can make a PR with the changes and we can follow up later this week.

**Comment by FuzzyStatic** [comment]
@jpleau I never received a response and your time format seems to work. https://github.com/FuzzyStatic/blizzard/releases/tag/v1.2.2

Thanks!

**Comment by jpleau** [comment]
I'm sorry I got a bit busy with other things. Thanks for merging this!
