### ISSUE TITLE
json: cannot unmarshal string into Go struct field CharacterProfileSummary.active_title

### ISSUE THREAD

**Issue by roffe** [FuzzyStatic/blizzard#37]
I'm running into some weird issues with some characters:

```
json: cannot unmarshal string into Go struct field CharacterProfileSummary.active_title of type struct { Key struct { Href string "json:\"href\"" } "json:\"key\""; Name string "json:\"name\""; ID int "json:\"id\""; DisplayString string "json:\"display_string\"" }`
```
Example characters where it happens:

us/hyjal/Deydorayn
us/bonechewer/Chaitwa
us/kiljaeden/Fearnøevil
us/emerald-dream/Heldin
eu/kazzak/Moonjumper

I have retry logic with back-off and the same error happens 10 times in a row on these characters so I don't think it was a temporary glitch

**Comment by roffe** [comment]
I will look into this in the weekend, just wanted to log it

**Comment by roffe** [comment]
I can confirm the bug, 

The characters that fail all have `active_title` as a single string and not in a structure 

`active_title : "Hand of A'dal"`

**Comment by roffe** [comment]
just for testing i changed the ActiveTitle to a interface{} and this is what i get from a assorted list of people:

```
Hand of A'dal
Ambassador
Jenkins
Jenkins
map[display_string:{name} the Elite Druid id:389 key:map[href:https://us.api.blizzard.com/data/wow/title/389?namespace=static-9.0.5_37760-us] name:the Elite Druid]
```

the last one is a normal response.

hmm, this gonna be a hard one to crack

**Comment by roffe** [comment]
```golang
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/FuzzyStatic/blizzard/v2"
)

var blizz *blizzard.Client

func init() {
	log.SetFlags(log.Lshortfile | log.LstdFlags)
	blizz = blizzard.NewClient(os.Getenv("BNET_ID"), os.Getenv("BNET_SECRET"), blizzard.US, blizzard.EnUS)
}

func main() {

	names := []string{
		//"us/hyjal/Deydorayn",
		"us/bonechewer/Chaitwa",
		"us/kiljaeden/Fearnøevil",
		"us/emerald-dream/Heldin",
		"us/illidan/Tomoboar",
	}

	for _, name := range names {
		parts := strings.Split(name, "/")
		_ = parts
		p, _, err := blizz.WoWCharacterProfileSummary(context.TODO(), parts[1], parts[2])
		if err != nil {
			log.Fatal(err)
		}

		fmt.Println(p.ActiveTitle)

	}
}
```
and i've modified characterProfile.go and made ActiveTitle it's own struct with a custom json unmarshaler

```golang
type ActiveTitle struct {
	Key struct {
		Href string `json:"href"`
	} `json:"key"`
	Name          string `json:"name"`
	ID            int    `json:"id"`
	DisplayString string `json:"display_string"`
}

func (u *ActiveTitle) UnmarshalJSON(data []byte) error {
	var v interface{}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch t := v.(type) {
	case map[string]interface{}:
		key := t["key"].(map[string]interface{})
		u.Name = t["name"].(string)
		u.ID = int(t["id"].(float64))
		u.DisplayString = t["display_string"].(string)
		u.Key.Href = key["href"].(string)
	case string:
		u.Name = t
		u.DisplayString = t
	}

	return nil
}
```

Output with modified type

```
{{} Ambassador 0 Ambassador}
{{} Jenkins 0 Jenkins}
{{} Jenkins 0 Jenkins}
{{https://us.api.blizzard.com/data/wow/title/389?namespace=static-9.0.5_37760-us} the Elite Druid 389 {name} the Elite Druid}
```

**Comment by roffe** [comment]
https://us.forums.blizzard.com/en/blizzard/t/api-inconsistent-response-for-activetitle/16648

**Comment by roffe** [comment]
We should probably await Blizzards response on this one before making ugly workarounds, I suspect they need to do a update of the characters or similar as they have data stored in a old format or similar

**Comment by FuzzyStatic** [comment]
@roffe thanks for doing the work on this! For now, we wait...

**Comment by francis-schiavo** [comment]
Hi there. I just replied to you forum post, I think those are old character data. Hope it helps.

**Comment by roffe** [comment]
@francis-schiavo thank you very much for the reply both here and on the forum!

@FuzzyStatic it's related to schema version as francis pointed out in the forum reply

```
When you request data from the API the API return 2 very important headers: Battlenet-Schema and Battlenet-Schema-Revision.

If you search for data on those characters you’ll notice the ones returning simple string are in revision 15 while the current revision is 24.
```

**Comment by roffe** [comment]
I guess the quick and dirty fix would be something along the code example I did earlier where we implement a custom UnmarshalJSON and for older schema versions we would just propagate the name field in the current struct

I can't come up with a much better solution right now without breaking the current API we have. Have to sleep on it and think some more how to tackle this.

Maybe we could make methods for retrieving data from the responses but that would require a lot of code to be written.

**Comment by FuzzyStatic** [comment]
Thanks @francis-schiavo and @roffe. When I have some time I'll think about how to implement revision into the API.
