### ISSUE TITLE
Unable to pull the latest version

### ISSUE THREAD

**Issue by leonidboykov** [FuzzyStatic/blizzard#58]
Hello!

I'm unable to pull the latest version (v3.0.2) with `go get -u github.com/FuzzyStatic/blizzard@v3.0.2` command:

```
go: github.com/FuzzyStatic/blizzard@v3.0.2: invalid version: module contains a go.mod file, so module path must match major version ("github.com/FuzzyStatic/blizzard/v3")
```

`go get -u github.com/FuzzyStatic/blizzard/v3@v3.0.2` does not work too.

It seems you pushed the v3.x.x tag but didn't update the module path to handle v3 versions (`module` in `go.mod` and imports).

**Comment by FuzzyStatic** [comment]
Fixed, try version 3.0.3
